"""Add view tracking fields to Content model

Revision ID: 2b6005e8ca82
Revises: b0c942b58f9f
Create Date: 2025-06-03 00:02:18.101427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6005e8ca82'
down_revision = 'b0c942b58f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('view_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_viewed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('last_viewed')
        batch_op.drop_column('view_time')
        batch_op.drop_column('views')

    # ### end Alembic commands ###
