"""Add questionnaire fields to UserSession model

Revision ID: ca6bad9757b5
Revises: 
Create Date: 2025-06-02 18:29:41.560632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6bad9757b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_session_id'))

    op.drop_table('ratings')
    op.drop_table('contents')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pre_questionnaire_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('post_questionnaire_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('questionnaire_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_column('questionnaire_data')
        batch_op.drop_column('post_questionnaire_completed')
        batch_op.drop_column('pre_questionnaire_completed')

    op.create_table('contents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('image', sa.VARCHAR(length=256), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=False),
    sa.Column('dislikes', sa.INTEGER(), nullable=False),
    sa.Column('shares', sa.INTEGER(), nullable=False),
    sa.Column('comments', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('rating_total', sa.INTEGER(), nullable=False),
    sa.Column('rating_count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('content_id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###
